### PR TITLE
Lock closed issues and pull requests after a period of inactivity

### PR DESCRIPTION
**Pull request by tkoyama010**
### Description

---
See https://github.com/pyvista/pyvista/pull/5489

### CODE REVIEW

**Comment by trexfeathers** [comment]
From my experience with the SciTools organization, an absence of conversation does not represent a lack of interest, but more likely sporadic funding of scientific projects. I have enjoyed the freedom given by the [`stale` action](https://github.com/bjlittle/geovista/blob/main/.github/workflows/ci-stale.yml), which implies:

>We've triaged this closed for now, as it doesn't seem to be important. If it becomes important again in the future you can let us know by commenting.

We've also found that users can discuss workarounds on issues/PRs even when they remain closed due to limited resource.

Merging this pull request would remove the above benefits. But presumably there are benefits I am missing?

**Comment by tkoyama010** [comment]
> From my experience with the SciTools organization, an absence of conversation does not represent a lack of interest, but more likely sporadic funding of scientific projects. I have enjoyed the freedom given by the [`stale` action](https://github.com/bjlittle/geovista/blob/main/.github/workflows/ci-stale.yml), which implies:
> 
> > We've triaged this closed for now, as it doesn't seem to be important. If it becomes important again in the future you can let us know by commenting.
> 
> We've also found that users can discuss workarounds on issues/PRs even when they remain closed due to limited resource.
> 
> Merging this pull request would remove the above benefits. But presumably there are benefits I am missing?

Good point. Perhaps I should be more tolerant of such actions from users. I made this suggestion because of the following concerns in the PyVista community and I thought it is also need to geovista.

- When there is a comment on a closed issue or PR, community members miss it at a high rate.
- A question after it has been closed is more likely to be another question in the fact that it was asked again. Even if the questions are similar, they can be linked together when a new Issue or PR is created.

Of course, I also welcome the decision to close this, as this operation is subject to consensus.

**Comment by bjlittle** [comment]
Hey @tkoyama010,

Thanks for this pull-request. I really appreciate you taking the time to play this forwards onto `geovista` 👍 

I was unaware of the `dessant/lock-threads` GHA, which is a pretty cool 🤩  

On reflection, we don't seem to have this problem at the moment on `geovista`. 

In fact, take a look at issue #620. This is a great example of a very recent issue that was raised by a user, but after some investigation we quickly realised that the root problem wasn't caused by `geovista` but another third-party package called [pykdtree](https://github.com/storpipfugl/pykdtree).

The user rightfully closed the issue, but the conversation then continued on the closed issue and resulted in a rather priceless open-source interaction where one of the core developers of `pykdtree` got involved. Between the users, the `pykdtree` core dev and myself we were able to help clarify (to an extent) the problem over on `pykdtree`.

This resulted in the issue https://github.com/storpipfugl/pykdtree/issues/106 being raised for the `pykdtree` community to raise awareness, and the subsequent pull-request https://github.com/storpipfugl/pykdtree/pull/107.

All of this wouldn't have been possible if the issue was auto-locked by the bot when it was closed by the user.

Given that example, would you mind if we didn't opt to use the lock bot? But monitor whether we need to come back to this if the occasion arises in the future?

Let me know what you think 🤔 

Thanks!

**Comment by tkoyama010** [comment]
> Hey @tkoyama010,
> 
> Thanks for this pull-request. I really appreciate you taking the time to play this forwards onto `geovista` 👍
> 
> I was unaware of the `dessant/lock-threads` GHA, which is really pretty cool 🤩
> 
> On reflection, we don't seem to have this problem at the moment on `geovista`.
> 
> In fact, take a look at issue #620. This is a great example of a very recent issue that was raised by a user, but after some investigation we quickly realised that the root problem wasn't caused by `geovista` but another third-party package called [pykdtree](https://github.com/storpipfugl/pykdtree).
> 
> The user rightfully closed the issue, but the conversation then continued on the closed issue and resulted in a rather priceless open-source interaction where one of the core developers of `pykdtree` got involved. Between the users, the `pykdtree` core dev and myself we were able to help clarify (to an extent) the problem over on `pykdtree`.
> 
> This resulted in the issue [storpipfugl/pykdtree#106](https://github.com/storpipfugl/pykdtree/issues/106) being raised for the `pykdtree` community to raise awareness, and the subsequent pull-request [storpipfugl/pykdtree#107](https://github.com/storpipfugl/pykdtree/pull/107).
> 
> All of this wouldn't have been possible if the issue was auto-locked by the bot when it was closed by the user.
> 
> Given that example, would you mind if we didn't opt to use the lock bot? But monitor whether we need to come back to this if the occasion arises in the future?
> 
> Let me know what you think 🤔
> 
> Thanks!

Thank you for your comment. I am 100% that problems should be addressed as they arise. In that sense, this proposal may have been too pre-emptive. Please use this solution if you encounter this problem in the future. This, PR is closed.

**Comment by bjlittle** [comment]
@ Yee, let's see if we need to come back to this 👍

Thanks for making me aware of this concern.

I feel bad that you've put the effort into a pull-request that's not been merged. I know that you're extremely busy, as always.

I don't want you to stop proposing better ways of working or challenging current workflow.

Perhaps if you're unsure about something, rather than create a pull request open a GH Discussion. That might be better in this particular case 

I'm going to remind myself to do that now often too 👍

**Comment by tkoyama010** [comment]
> Perhaps if you're unsure about something, rather than create a pull request open a GH Discussion. That might be better in this particular case

Yes. That's a better behavior :+1:

**Pull request closed without merging**
