### PR TITLE
[TEST] pytest-pyvista and osmesa

### PR DESCRIPTION
**Pull request by bjlittle**
### Description

This is just a WIP investigation to see the `pytest-pyvista` behaviour with the newly rendered `conda` lockfiles, which now contain the `osmesa` build of `vtk`.

This pull-request will be closed in favour of #450 

---

### CODE REVIEW

**Comment by bjlittle** [comment]
@tkoyama010 and @MatthewFlamm

Wow! It actually executed the image test!

However, the image comparison difference failed :cry: 

Is there an easy way to see the image comparison difference ?

**Comment by MatthewFlamm** [comment]
Below is the way we did it in `pytest-pyvista`  I thought we had done this in pyvista too, but it doesn't look like it.  Also now that I've checked we are running using xvfb in both pyvista and pytest-pyvista tests.

https://github.com/pyvista/pytest-pyvista/blob/42f771b84fd99d98a1e202f432ee56a9773e8f05/.github/workflows/ci_cd.yml#L174-L183

**Comment by bjlittle** [comment]
> Below is the way we did it in `pytest-pyvista` I thought we had done this in pyvista too, but it doesn't look like it. Also now that I've checked we are running using xvfb in both pyvista and pytest-pyvista tests.
> 
> https://github.com/pyvista/pytest-pyvista/blob/42f771b84fd99d98a1e202f432ee56a9773e8f05/.github/workflows/ci_cd.yml#L174-L183

@MatthewFlamm Awesome, thanks! ... I've been hunting around the `pyvista` code base looking for clues :detective: 

So `pyvista` is not using `osmesa` but `qt` and `xvfb`, right?

**Comment by MatthewFlamm** [comment]
> So `pyvista` is not using `osmesa`, but `qt` and `xvfb`, right?

I think it has ebbed and flowed over time, but I don't see osmesa being used in the normal CI today.

https://github.com/pyvista/pyvista/blob/83ff2174d1461f297b4267a0711bf178b32d7ac3/.github/workflows/testing-and-deployment.yml#L200-L201

There is a bit of CI added to preview vtk 9.3.0 that uses osmesa.  I do not have a suggested method as I don't know the pros and cons of both very closely.  I just know that you have to do one or the other.

**Comment by bjlittle** [comment]
@MatthewFlamm Just discovered https://github.com/The-Compiler/pytest-xvfb ... looks interesting

You come across it before or use it?

**Comment by MatthewFlamm** [comment]
> @MatthewFlamm Ohhh just discovered https://github.com/The-Compiler/pytest-xvfb ... looks interesting 😮
> 
> You come across it before or use it?

It does look interesting, but I'm not sure that it is simpler than doing `xvfb-run` for these simple cases.  It looks like it might be useful if you need the command to work in several types of environments.

**Pull request closed without merging**
