### PR TITLE
Adopt pytest-pyvista and qt/xvfb

### LINKED ISSUE #429: Using pytest-pyvista to improve tests of geovista
## 📰 Custom Issue

[pytest-pyvista](https://github.com/pyvista/pytest-pyvista) is a plugin to test PyVista plot outputs.
We can add tests of geovista's plotting using this.

### PR DESCRIPTION
**Pull request by bjlittle**
### Description

This is just a WIP investigation to see the `pytest-pyvista` behaviour with the `qt` build of `vtk` and using `xvfb`.

This pull-request will be closed in favour of #450.

Closes #429

---

### CODE REVIEW

**Comment by bjlittle** [comment]
@tkoyama010 Very interesting ... this works! Although the test fails with an image difference.

However, pushing the `xvfb-run` down into `tox` is required to make this behave with the QT bindings of `vtk`.

We may be able to ditch the use of `xvfb-run` within `tox` in favour of using [pytest-xvfb](https://github.com/The-Compiler/pytest-xvfb), as I don't want calls to `xvfb-run` polluting `tox`.

So for me this is a decent step forwards ... I'll continue this exploration tomorrow :+1:

**Comment by tkoyama010** [comment]
@bjlittle It's happy to hear that you solved this problem. I will refer to this to update #450 .

**Comment by bjlittle** [comment]
@tkoyama010 Okay, so the pattern within the PR is now working for image testing in CI with `pytest-pyvista`.

In summary,
- we apt install `libgl1-mesa-glx` and `xvfb` and cache within the GHA
- we adopt the usage of the `pytest-xvfb` package to essentially `xvfb-run`
- we capture and upload test output images on failure, these assets can then be downloaded for analysis
- reverted the use of the `off_screen` kwarg in the examples and instead adopt `pyvista.OFF_SCREEN = True` when image testing
- continue to use the QT bindings of `vtk`

Please adopt these changes in #450. I'm keen for you to bank that pull-request with these changes, as you initiated the image test coverage for `geovista` :star_struck: 

Note that, you'll also need to rebase your pull-request #450 to include further changes merged onto `main`.

Once we've banked #450, I'm going to refactor the approach for image testing to extend it for the other tests, but also look to version control the base `image_cache` outside `geovista` i.e., the `image_cache` assets will be downloaded on-demand when testing

**Comment by bjlittle** [comment]
@tkoyama010 I'm super keen to push this forwards, so I'm just going to bank it and follow-up on refactoring and improving the pattern to auto-generate image tests for the rest of the examples, with downloadable baseline image assets.

Hope you don't mind 😉

**Comment by tkoyama010** [comment]
@tkoyama010 I don't mind at all! Significant improvement of the test of GeoVista!

**Pull request merged**
