### PR TITLE
Add `taplo` pre-commit hook to format and sort `toml` files

### LINKED ISSUE #1205: Add `taplo` pre-commit hook to format and sort `toml` files
[taplo](https://github.com/tamasfe/taplo) is an awesome tool and I recommend its use.
ref https://github.com/pyvista/pyvista/pull/6781

### PR DESCRIPTION
**Pull request by tkoyama010**
### Description

resolve #1205

---

### CODE REVIEW

**Comment by tkoyama010** [comment]
pre-commit.ci autofix

**Review by bjlittle — APPROVED** [review]
@tkoyama010 Awesome, thanks! :1st_place_medal: 

LGTM :+1:

**Comment by bjlittle** [comment]
@tkoyama010 You need to add a changelog news fragment, see [here](https://geovista.readthedocs.io/en/latest/developer/index.html#changelog).

I'd suggest its type is a `contributor` change :+1:

**Review by bjlittle — CHANGES_REQUESTED** [review]
@tkoyama010 You need to add a changelog news fragment, see [here](https://geovista.readthedocs.io/en/latest/developer/index.html#changelog).

I'd suggest its type is a `contributor` change :+1:

**Review by bjlittle — APPROVED** [review]
@tkoyama010 Awesome effort, thanks! :trophy: 

Keen to get this banked before it goes stale :+1:

**Pull request merged**
