### PR TITLE
Add sample earthquake example

### PR DESCRIPTION
**Pull request by tkoyama010**
## 🚀 Pull Request

See #373

### Description

Add an earthquake sample. This is not perfect (We need to express the scalar by the color of size) but good to go.

---

### CODE REVIEW

**Comment by tkoyama010** [comment]
pre-commit.ci autofix

**Comment by tkoyama010** [comment]
pre-commit.ci autofix

**Comment by tkoyama010** [comment]
pre-commit.ci autofix

**Review by bjlittle — APPROVED** [review]
@tkoyama010 Thanks, this is amazing! :star_struck: 

I'm reconsidering bringing back `geovista.geoplotter.GeoPlotter.add_points` as a convenience so that you can simply pass in the longitudes and latitudes and the conversion to cartesian is done for you. I'll have a think about this.

Plus auto-scaling the points when zooming might be a future consideration.

Anyways, I really love this contribution. It's super cool! :100: :beers:

**Comment by bjlittle** [comment]
@all-contributors please add @tkoyama010 for code, data, example, ideas

**Comment by tkoyama010** [comment]
@allcontributors
please add @bjlittle eventOrganizing
please add @tkoyama010 eventOrganizing

**Comment by tkoyama010** [comment]
@allcontributors
please add @bjlittle for eventOrganizing
please add @tkoyama010 for eventOrganizing

**Comment by tkoyama010** [comment]
@allcontributors
please add @tkoyama010 for eventOrganizing

**Comment by tkoyama010** [comment]
@allcontributors
please add @bjlittle for mentoring

**Comment by tkoyama010** [comment]
> I've updated

Oh. You are good.

**Pull request merged**
