### PR TITLE
Stop doubling up PR checks

### PR DESCRIPTION
**Pull request by trexfeathers**
### Description

This prevents each PR check on pushes to a 'bot branch' (see screenshot below), since these all go via a pull request anyway and the checks get run from that trigger.

image

---

### CODE REVIEW

**Comment by trexfeathers** [comment]
Confused! Maybe the doubling up only happens on Bot PR's?

**Comment by trexfeathers** [comment]
I think this is OK now.

**Comment by bjlittle** [comment]
Nice one, thanks @trexfeathers 👍

**Comment by bjlittle** [comment]
@all-contributors add @trexfeathers for infrastructure

**Comment by bjlittle** [comment]
@all-contributors please add @trexfeathers for infra

**Pull request merged**
