### PR TITLE
migrate to >=py311 enum.StrEnum usage

### PR DESCRIPTION
**Pull request by bjlittle**
### Description

After adopting [Scientific Python SPEC-0](https://scientific-python.org/specs/spec-0000/) and dropping support of `py310`, we're now free to adopt [enum.StrEnum](https://docs.python.org/3/library/enum.html#enum.StrEnum) and [enum.auto](https://docs.python.org/3/library/enum.html#enum.auto) and thus purge some tech debt.

---

### CODE REVIEW

**Comment by trexfeathers** [comment]
Are you sure about `auto()`? With explicit strings we still get the built-in validation and documentation of `Enum`, while allowing users to type strings in their own code, which I imagine would be easier.

**Comment by bjlittle** [comment]
Users can still type strings as before, so there's no difference in user experience or behaviour. 

When `auto()` is used for a `StrEnum` it's giving us the lower case string of the enumeration name for free ... the only difference is in the rendered documentation where the value of an enumeration isn't shown i.e., this ...

image

vs this ...

image

TBH on reflection I prefer the former, so if you wanted to push a PR dropping the use of `auto`, that would be welcomed 😉

**Comment by trexfeathers** [comment]
Ohhhh now I can't decide 😖

>it's giving us the lower case string value of the enumeration name for free

That's good!

>the rendered documentation where the value of an enumeration isn't shown

That's bad!

>TBH on reflection I prefer the former

Let me know if you're just being nice. If you really want it I will write it!

**Comment by trexfeathers** [comment]
#1152

**Pull request merged**
